version: '3.7'
services:
  db:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: feathers
      MYSQL_ROOT_PASSWORD: root
  node:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - .:/var/app
    ports:
      - '3030:3030'
      - '9229:9229'
volumes:
  mysql:
    driver: local
